"""add  last_seen and about_me

Revision ID: 17acbeedd84c
Revises: 828b6287acce
Create Date: 2018-03-24 18:08:54.889836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17acbeedd84c'
down_revision = '828b6287acce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
